services:
  nginx:
    build: ./enshi
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge